language: node_js
node_js:
  - "10"
dist: bionic
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- npm run test-headless
- ng build --prod --base-href https://bunop.github.io/ng-leaflet-etude/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ng-leaflet-etude
  on:
    branch: master
